{{config(
    tags=["sbc"]
    ,pre_hook=mpre_hook(c_package="SBC", c_status="RUNNING", c_bookmark="AFTER_STG")
    )}}

SELECT 
    SBC_ID,
    SBC_DESC,
    CLS.CLS_KEY as CLS_KEY,
    CLS.CLS_ID as CLS_ID,
    CLS.CLS_DESC as CLS_DESC,
    DPT.DPT_KEY as DPT_KEY,
    DPT.DPT_ID as DPT_ID,
    DPT.DPT_DESC as DPT_DESC,
    GRP.GRP_KEY as GRP_KEY,
    GRP.GRP_ID as GRP_ID,
    GRP.GRP_DESC as GRP_DESC,
    GRP.DIV_KEY as DIV_KEY,
    GRP.DIV_ID as DIV_ID,
    GRP.DIV_DESC as DIV_DESC,
    GRP.COMPANY_KEY as COMPANY_KEY,
    GRP.COMPANY_ID as COMPANY_ID,
    GRP.COMPANY_DESC as COMPANY_DESC,
    RMS_SBCLASS_MRCH_IDNT,
    RMS_SBCLASS_BUYR_IDNT,
    RMS_Q_IMG_LG,
    SBC.RMS_LOAD_DATE as RMS_LOAD_DATE,
    RMS_Q_IMG_DFLT,
    RMS_SBCLASS_MRCH_NAME,
    RMS_SBCLASS_BUYR_NAME,
    RMS_Q_IMG_SM,
    RMS_Q_DPT_SNUM,
    RMS_Q_DPT_DNUM,
    SBC.RMS_SRC_ID as RMS_SRC_ID,
    RMS_Q_SBC_SDESC

FROM {{ref('V_STG_D_PRD_SBC_LU')}} as SBC 
LEFT OUTER JOIN {{ref('DWH_D_PRD_CLS_LU')}} as CLS on SBC.CLS_ID = CLS.CLS_ID
LEFT OUTER JOIN {{ref('DWH_D_PRD_DPT_LU')}} as DPT on SBC.DPT_ID = DPT.DPT_ID
LEFT OUTER JOIN {{ref('DWH_D_PRD_GRP_LU')}} as GRP on SBC.GRP_ID = GRP.GRP_ID