{{config(
    tags=["ara"]
    ,pre_hook=mpre_hook(c_package="ARA", c_status="RUNNING", c_bookmark="AFTER_STG")
    )}}

SELECT
    ARA_ID,
    ARA.ARA_DESC as ARA_DESC,
    CHN.CHN_KEY as CHN_KEY,
    CHN.CHN_ID as CHN_ID,
    CHN.CHN_DESC as CHN_DESC,
    COMPANY.COMPANY_KEY as COMPANY_KEY,
    COMPANY.COMPANY_DESC as COMPANY_DESC,
    COMPANY.COMPANY_ID as COMPANY_ID,
    ARA.ARA_MGR_FIRST_NAME as ARA_MGR_FIRST_NAME,
    ARA.ARA_MGR_LAST_NAME as ARA_MGR_LAST_NAME,
    ARA.ARA_MGR_HOME_STR as ARA_MGR_HOME_STR ,
    ARA.ARA_MGR_MAIL_EXT as ARA_MGR_MAIL_EXT,
    ARA.ARA_MGR_COUNTRY_CDE as ARA_MGR_COUNTRY_CDE,
    ARA.ARA_MGR_ASSISTANT_NAME as ARA_MGR_ASSISTANT_NAME,
    ARA.ARA_MGR_MOBILE as ARA_MGR_MOBILE,
    ARA.RMS_Q_CPY_DNUM as RMS_Q_CPY_DNUM,
    ARA.RMS_Q_CPY_SDESC as RMS_Q_CPY_SDESC
FROM {{ref('V_STG_D_ORG_ARA_LU')}} AS ARA
LEFT OUTER JOIN {{ref('DWH_D_ORG_COMPANY_LU')}} AS COMPANY on ARA.COMPANY_ID = COMPANY.COMPANY_ID
LEFT OUTER JOIN {{ref('DWH_D_ORG_CHN_LU')}} AS CHN on ARA.CHN_ID = CHN.CHN_ID




