
{{config(
	tags=["chn"]
	,pre_hook=mpre_hook(c_package="CHN", c_status="RUNNING", c_bookmark="AFTER_STG")
	)}}

SELECT 
    CHN.CHN_ID as CHN_ID,
    CHN.CHN_DESC as CHN_DESC,
    COMPANY.COMPANY_KEY as COMPANY_KEY, CHN.COMPANY_ID as COMPANY_ID, COMPANY.COMPANY_DESC as COMPANY_DESC,
    CHN.CHN_MGR_FIRST_NAME as CHN_MGR_FIRST_NAME,
	CHN.CHN_MGR_LAST_NAME as CHN_MGR_LAST_NAME,
	CHN.CHN_MGR_HOME_STR as CHN_MGR_HOME_STR,
	CHN.CHN_MGR_PHONE as CHN_MGR_PHONE,
	CHN.CHN_MGR_MAIL_EXT as CHN_MGR_MAIL_EXT,
	CHN.CHN_MGR_COUNTRY_CDE as CHN_MGR_COUNTRY_CDE,
	CHN.CHN_MGR_ASSISTANT_NAME as CHN_MGR_ASSISTANT_NAME,
	CHN.CHN_MGR_MOBILE as CHN_MGR_MOBILE,
	CHN.RMS_BRND_DNUM as RMS_BRND_DNUM,
	CHN.RMS_BRND_SDESC as RMS_BRND_SDESC,
	CHN.RMS_SRC_ID as RMS_SRC_ID
FROM
	{{ref('V_STG_D_ORG_CHN_LU')}} as CHN 
	LEFT OUTER JOIN {{ref('DWH_D_ORG_COMPANY_LU')}} COMPANY on CHN.COMPANY_ID = COMPANY.COMPANY_ID

	
